
package calcC;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SimpleCalculatorService", targetNamespace = "http://chapter3.webreading.farkalit.com/calc", wsdlLocation = "http://localhost:8040/calc?wsdl")
public class SimpleCalculatorService
    extends Service
{

    private final static URL SIMPLECALCULATORSERVICE_WSDL_LOCATION;
    private final static WebServiceException SIMPLECALCULATORSERVICE_EXCEPTION;
    private final static QName SIMPLECALCULATORSERVICE_QNAME = new QName("http://chapter3.webreading.farkalit.com/calc", "SimpleCalculatorService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8040/calc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIMPLECALCULATORSERVICE_WSDL_LOCATION = url;
        SIMPLECALCULATORSERVICE_EXCEPTION = e;
    }

    public SimpleCalculatorService() {
        super(__getWsdlLocation(), SIMPLECALCULATORSERVICE_QNAME);
    }

    public SimpleCalculatorService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIMPLECALCULATORSERVICE_QNAME, features);
    }

    public SimpleCalculatorService(URL wsdlLocation) {
        super(wsdlLocation, SIMPLECALCULATORSERVICE_QNAME);
    }

    public SimpleCalculatorService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIMPLECALCULATORSERVICE_QNAME, features);
    }

    public SimpleCalculatorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SimpleCalculatorService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SimpleCalculator
     */
    @WebEndpoint(name = "SimpleCalculatorPort")
    public SimpleCalculator getSimpleCalculatorPort() {
        return super.getPort(new QName("http://chapter3.webreading.farkalit.com/calc", "SimpleCalculatorPort"), SimpleCalculator.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SimpleCalculator
     */
    @WebEndpoint(name = "SimpleCalculatorPort")
    public SimpleCalculator getSimpleCalculatorPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://chapter3.webreading.farkalit.com/calc", "SimpleCalculatorPort"), SimpleCalculator.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIMPLECALCULATORSERVICE_EXCEPTION!= null) {
            throw SIMPLECALCULATORSERVICE_EXCEPTION;
        }
        return SIMPLECALCULATORSERVICE_WSDL_LOCATION;
    }

}
