
package calcC;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SimpleCalculator", targetNamespace = "http://chapter3.webreading.farkalit.com/calc")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SimpleCalculator {


    /**
     * 
     * @param input
     * @return
     *     returns java.lang.String
     * @throws CalcException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "operation", targetNamespace = "http://chapter3.webreading.farkalit.com/calc", className = "calcC.Operation")
    @ResponseWrapper(localName = "operationResponse", targetNamespace = "http://chapter3.webreading.farkalit.com/calc", className = "calcC.OperationResponse")
    @Action(input = "http://chapter3.webreading.farkalit.com/calc/SimpleCalculator/operationRequest", output = "http://chapter3.webreading.farkalit.com/calc/SimpleCalculator/operationResponse", fault = {
        @FaultAction(className = CalcException_Exception.class, value = "http://chapter3.webreading.farkalit.com/calc/SimpleCalculator/operation/Fault/CalcException")
    })
    public String operation(
        @WebParam(name = "input", targetNamespace = "")
        String input)
        throws CalcException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findSymbol", targetNamespace = "http://chapter3.webreading.farkalit.com/calc", className = "calcC.FindSymbol")
    @ResponseWrapper(localName = "findSymbolResponse", targetNamespace = "http://chapter3.webreading.farkalit.com/calc", className = "calcC.FindSymbolResponse")
    @Action(input = "http://chapter3.webreading.farkalit.com/calc/SimpleCalculator/findSymbolRequest", output = "http://chapter3.webreading.farkalit.com/calc/SimpleCalculator/findSymbolResponse")
    public String findSymbol(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
