delimiter $$

CREATE TABLE `user` (
  `USER_ID` int(5) NOT NULL,
  `USERNAME` varchar(20) NOT NULL,
  `CREATED_BY` varchar(20) NOT NULL,
  `CREATED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1$$


