/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.farkalit.util;

import java.util.UUID;

/**
 * Starting with Java 5, the UUID class provides a simple means for generating unique ids.
 * The identifiers generated by UUID are actually universally unique identifiers.
 *
 * @author 72010995
 */
public class UUIDSample
{

    public static final void main(String... aArgs)
    {
        //generate random UUIDs
        UUID idOne = UUID.randomUUID();
        UUID idTwo = UUID.randomUUID();
        log("UUID One: " + idOne);
        log("UUID Two: " + idTwo);
    }

    private static void log(Object aObject)
    {
        System.out.println(String.valueOf(aObject));
    }
}
