
package calcCHR;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "CalcException", targetNamespace = "http://chapter3.webreading.farkalit.com/calc")
public class CalcException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private CalcException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public CalcException_Exception(String message, CalcException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public CalcException_Exception(String message, CalcException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: calcCHR.CalcException
     */
    public CalcException getFaultInfo() {
        return faultInfo;
    }

}
