
package fibC;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RabbitCounter", targetNamespace = "http://chapter3.webreading.farkalit.com/fibc")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RabbitCounter {


    /**
     * 
     * @param num
     * @return
     *     returns int
     * @throws FibException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "countRabbits", targetNamespace = "http://chapter3.webreading.farkalit.com/fibc", className = "fibC.CountRabbits")
    @ResponseWrapper(localName = "countRabbitsResponse", targetNamespace = "http://chapter3.webreading.farkalit.com/fibc", className = "fibC.CountRabbitsResponse")
    @Action(input = "http://chapter3.webreading.farkalit.com/fibc/RabbitCounter/countRabbitsRequest", output = "http://chapter3.webreading.farkalit.com/fibc/RabbitCounter/countRabbitsResponse", fault = {
        @FaultAction(className = FibException_Exception.class, value = "http://chapter3.webreading.farkalit.com/fibc/RabbitCounter/countRabbits/Fault/FibException")
    })
    public int countRabbits(
        @WebParam(name = "num", targetNamespace = "")
        int num)
        throws FibException_Exception
    ;

}
